name: openset-imagenet-comparison

channels:
  - default
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  - pandas>=1.4.3
  - numpy>=1.22.3
  - matplotlib>=3.5.2
  - scikit-learn>=1.1.1
  - cudatoolkit>=11
  - pytorch>=1.11.0
  - torchvision>=0.12.0
  - loguru>=0.6.0
  - tqdm>=4.64.0
  - pyyaml
  - pip
  - tensorboard
  - pip:
      - robustness>=1.2.1.post2
      - git+https://github.com/Vastlab/vast.git
      - -e . # install this package as well
